version: '3.8'
services:

  mysqlserver:
    image: mysql
    container_name: mysql-medical-app-container
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: ["mysqld", "--mysql-native-password=ON"]
    ports:
      - "3306:3306"
    networks:
      - net
    volumes:
      - sql_data:/var/opt/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  backend:
    build:
      context: ./backend
      args:
        PROFILE: ${PROFILE}
    container_name: backend-medical-app-container
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8089:8089"
    networks:
      - net
    depends_on:
      - mysqlserver

  frontend:
    build:
      context: ./frontend
      args:
        PROFILE: ${PROFILE}
    container_name: frontend-medical-app-container
    depends_on:
      - mysqlserver
      - backend
    ports:
      - "4209:80"
    volumes:
      - ./frontend:/app
    networks:
      - net

networks:
  net:

volumes:
  sql_data:
