package com.medical.app.employee.enums;

public enum SpecializationEnum {
  NONE,
  CARDIOLOGY,
  DERMATOLOGY,
  ENDOCRINOLOGY,
  GASTROENTEROLOGY,
  GYNECOLOGY,
  HEMATOLOGY,
  NEPHROLOGY,
  NEUROLOGY,
  ONCOLOGY,
  OPHTHALMOLOGY,
  ORTHOPEDICS,
  OTOLARYNGOLOGY,
  PEDIATRICS,
  PSYCHIATRY,
  PULMONOLOGY,
  RHEUMATOLOGY,
  UROLOGY
}
