name: "[FE][DEV] Deploy to DockerHub and SSH"

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image and Push
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: stefanpatrascu/medlink-frontend-${{ vars.PROFILE }}:latest
          build-args: |
            PROFILE=${{ vars.PROFILE }}

      - name: Deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p $${{ secrets.DOCKER_PASSWORD }}
            docker image pull stefanpatrascu/medlink-frontend-${{ vars.PROFILE }}:latest
            docker container stop medlink-frontend-${{ vars.PROFILE }}
            docker container rm medlink-frontend-${{ vars.PROFILE }}
            docker container run \
            -d --name medlink-frontend-${{ vars.PROFILE }} \
            --restart on-failure \
            -p 127.0.0.1:8080:8080 \
            --network mysql_redis_shared \
            stefanpatrascu/medlink-frontend-${{ vars.PROFILE }}:latest
            docker logout